### ISSUE TITLE
bungeecord使用check命令时报NoClassDefErr

### ISSUE THREAD

**Issue by ghost** [leavessoft/EusUniBan#6]
```
11:36:01 [严重] Exception in thread "main"
11:36:01 [严重] java.lang.NoClassDefFoundError: org.bukkit.Bukkit
11:36:01 [严重]     at cc.eumc.uniban.controller.CommandController.executeCommand(CommandController.java:48)
11:36:01 [严重]     at cc.eumc.uniban.command.BungeeCommand.execute(BungeeCommand.java:22)
11:36:01 [严重]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192)
11:36:01 [严重]     at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
11:36:01 [严重]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:69)
11:36:01 [严重]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:36:01 [严重] Caused by:
11:36:01 [严重] java.lang.ClassNotFoundException: org.bukkit.Bukkit
11:36:01 [严重]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
11:36:01 [严重]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
11:36:01 [严重]     at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
11:36:01 [严重]     ... 6 more
```

**Comment by richardhyy** [comment]
I've been working on this problem. Thank you for reporting.

**Comment by richardhyy** [comment]
Already fixed.
